#!/bin/bash

#(sleep 1 && setxkbmap -option ctrl:caps) &
(sleep 1 && gnome-keyring-daemon --components=gpg,pkcs11,secrets,ssh) &
(sleep 1 && setxkbmap -option ctrl:nocaps) &

(sleep 1 && gnome-settings-daemon) &
(sleep 4 && killall syndaemon; syndaemon -i 0.2 -k -d ) &
(sleep 4 && killall compton; compton) & 

(sleep 1 && wallpaper.sh planets_kurg.png ) &
(sleep 1 && screens.sh ) &
(sleep 3 && xrdb ~/.Xresources) &
(killall taffybar-linux-x86_64; sleep 3; taffybar) &

(sleep 3 && killall nm-applet; nm-applet) &
(sleep 1 && megasync ) &




